"""M1 leads locations staff events

Revision ID: 4c62a0043225
Revises: 
Create Date: 2026-06-19 20:02:31.456075
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c62a0043225'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('showroom', 'workshop', name='locationtype', native_enum=False, length=40), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('staff_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('sales_exec', 'manager', 'admin', name='staffrole', native_enum=False, length=40), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_staff_members_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_members'))
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('source', sa.Enum('walk_in', 'csv_import', 'form', name='leadsource', native_enum=False, length=40), nullable=False),
    sa.Column('interested_model', sa.String(length=80), nullable=True),
    sa.Column('budget', sa.String(length=60), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('preferred_language', sa.Enum('en', 'hi', 'te', name='language', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'engaged', 'test_drive_requested', 'feedback_given', 'handed_off', 'won', 'lost', 'opted_out', 'unreachable', name='leadstatus', native_enum=False, length=40), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('opt_out', sa.Boolean(), nullable=False),
    sa.Column('open_question', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['staff_members.id'], name=op.f('fk_leads_assigned_to_id_staff_members')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_leads_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('phone', name='uq_leads_phone')
    )
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_events_lead_id_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('staff_members')
    op.drop_table('locations')
    # ### end Alembic commands ###
