"""M2 messages scheduled_touches

Revision ID: ac6955deb292
Revises: 4c62a0043225
Create Date: 2026-06-19 20:46:21.362735
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6955deb292'
down_revision: Union[str, None] = '4c62a0043225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='messagedirection', native_enum=False, length=40), nullable=False),
    sa.Column('kind', sa.Enum('template', 'text', name='messagekind', native_enum=False, length=40), nullable=False),
    sa.Column('template_name', sa.String(length=80), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'read', 'failed', name='messagestatus', native_enum=False, length=40), nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('step_key', sa.String(length=40), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_messages_lead_id_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_provider_message_id'), 'messages', ['provider_message_id'], unique=False)
    op.create_table('scheduled_touches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(length=40), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'cancelled', 'skipped', 'failed', name='touchstatus', native_enum=False, length=40), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_scheduled_touches_lead_id_leads')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_scheduled_touches_message_id_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_touches'))
    )
    op.create_index(op.f('ix_scheduled_touches_scheduled_for'), 'scheduled_touches', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_touches_status'), 'scheduled_touches', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_touches_status'), table_name='scheduled_touches')
    op.drop_index(op.f('ix_scheduled_touches_scheduled_for'), table_name='scheduled_touches')
    op.drop_table('scheduled_touches')
    op.drop_index(op.f('ix_messages_provider_message_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
